# Setup
title:            Data Science Blog
tagline:          'Claudio'
description:      'Hi! I'm <a href="https://cclaudio.dev/about">Claudio</a> and this is my website about DS.'
url:              https://cclaudio.dev
baseurl:          '/'
paginate:         5

# About and contact
author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:          3.0.0
